'use client'

import { useState } from 'react'
import Link from 'next/link'
import {
  FileAudio,
  FileVideo,
  FileText,
  FileCode,
  Check,
  Copy,
  Sparkles,
  ArrowRight,
  UploadCloud,
  CheckCircle2,
  Layers,
  Clock,
  Sliders,
  Globe,
  Film
} from 'lucide-react'
import { MAX_MEDIA_UPLOAD_MB } from '@/lib/uploadLimits'

type ExportFormatKey = 'txt' | 'srt' | 'vtt' | 'json'

interface FormatSample {
  name: string
  extension: string
  badge: string
  bestFor: string
  desc: string
  sample: string
}

const EXPORT_FORMATS: Record<ExportFormatKey, FormatSample> = {
  txt: {
    name: 'Plain Text',
    extension: '.txt',
    badge: 'Reading & Notes',
    bestFor: 'Notion, Word, Google Docs, AI summaries',
    desc: 'Pure, clean transcript text stripped of timecodes. Optimal for reading, executive summaries, meeting minutes, and copy-pasting.',
    sample: `The meeting commenced promptly at 09:00 AM. The team discussed the Q3 product roadmap, focusing on audio processing efficiency, AI transcription precision, and automated subtitle generation for multi-language video content. Overall progress remains ahead of schedule with key milestones met across all departments.`
  },
  srt: {
    name: 'SubRip Subtitles',
    extension: '.srt',
    badge: 'Video Editors',
    bestFor: 'Premiere Pro, DaVinci Resolve, Final Cut, YouTube',
    desc: 'The global standard for video subtitles. Formatted with sequential cue indexes and millisecond timestamps using comma separators.',
    sample: `1
00:00:01,200 --> 00:00:04,800
The meeting commenced promptly at 09:00 AM.

2
00:00:05,100 --> 00:00:09,400
The team discussed the Q3 product roadmap, focusing on audio processing.

3
00:00:09,800 --> 00:00:14,200
Overall progress remains ahead of schedule with key milestones met.`
  },
  vtt: {
    name: 'WebVTT Captions',
    extension: '.vtt',
    badge: 'HTML5 Video',
    bestFor: 'Web players, Vimeo, Safari, Chrome, Video.js',
    desc: 'World Wide Web Consortium (W3C) standard for web video text tracks. Fully supported by native HTML5 <video> elements and modern web browsers.',
    sample: `WEBVTT - Generated by Signal AI

00:01.200 --> 00:04.800
The meeting commenced promptly at 09:00 AM.

00:05.100 --> 00:09.400
The team discussed the Q3 product roadmap, focusing on audio processing.

00:09.800 --> 00:14.200
Overall progress remains ahead of schedule with key milestones met.`
  },
  json: {
    name: 'Structured JSON',
    extension: '.json',
    badge: 'Developers & APIs',
    bestFor: 'Custom pipelines, search indexers, automation',
    desc: 'Rich JSON schema providing word-level or segment-level metadata, durations, speaker identifiers, and raw text payload.',
    sample: `{
  "transcription": "The meeting commenced promptly at 09:00 AM...",
  "meta": {
    "durationSeconds": 14.2,
    "wordCount": 38,
    "language": "en",
    "model": "Signal Gemini Pro"
  },
  "segments": [
    {
      "id": 1,
      "start": 1.2,
      "end": 4.8,
      "text": "The meeting commenced promptly at 09:00 AM."
    },
    {
      "id": 2,
      "start": 5.1,
      "end": 9.4,
      "text": "The team discussed the Q3 product roadmap."
    }
  ]
}`
  }
}

const AUDIO_FORMATS = [
  { ext: 'MP3', name: 'MPEG-1 Audio Layer III', desc: 'Universally compatible compressed audio' },
  { ext: 'WAV', name: 'Waveform Audio File', desc: 'Studio lossless uncompressed PCM audio' },
  { ext: 'M4A', name: 'MPEG-4 Audio', desc: 'High-efficiency AAC encoding (Apple Voice Memos)' },
  { ext: 'AAC', name: 'Advanced Audio Coding', desc: 'High sound quality at lower bitrates' },
  { ext: 'OGG', name: 'Ogg Vorbis / Opus', desc: 'Open container for voice & streaming' },
  { ext: 'FLAC', name: 'Free Lossless Audio Codec', desc: 'Bit-perfect compression for audiophile sources' }
]

const VIDEO_FORMATS = [
  { ext: 'MP4', name: 'MPEG-4 Part 14', desc: 'Industry standard for web & mobile video' },
  { ext: 'WEBM', name: 'WebM Project', desc: 'HTML5 web video (VP8/VP9/AV1 + Opus)' },
  { ext: 'MOV', name: 'Apple QuickTime', desc: 'Native macOS, iPhone & camera recordings' },
  { ext: 'M4V', name: 'iTunes Video Format', desc: 'Apple video container with AAC audio' },
  { ext: 'AVI', name: 'Audio Video Interleave', desc: 'Legacy Windows multimedia container' },
  { ext: 'MKV', name: 'Matroska Video', desc: 'Flexible container with multi-track support' }
]

const COMPATIBLE_TOOLS = [
  'Adobe Premiere Pro',
  'DaVinci Resolve',
  'Final Cut Pro',
  'CapCut',
  'YouTube Studio',
  'Notion',
  'Google Docs',
  'Microsoft Word',
  'VLC Media Player'
]

export default function FormatsPage() {
  const [activeTab, setActiveTab] = useState<ExportFormatKey>('txt')
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(EXPORT_FORMATS[activeTab].sample)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // ignore
    }
  }

  return (
    <div className="mx-auto w-full max-w-6xl px-4 pb-24 pt-8 sm:px-6 sm:pt-12">
      {/* Header Section */}
      <header className="mx-auto mb-12 max-w-3xl text-center">
        <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-blue-500/20 bg-blue-50/80 dark:bg-blue-950/40 px-3.5 py-1 text-xs font-semibold text-blue-600 dark:text-blue-400 backdrop-blur-md shadow-2xs">
          <Sparkles className="h-3.5 w-3.5" />
          <span>Specifications & Capabilities Guide</span>
        </div>
        <h1 className="text-3xl font-bold tracking-tight text-slate-950 dark:text-white sm:text-5xl">
          Supported Formats & Specs
        </h1>
        <p className="mt-3 text-base leading-relaxed text-slate-600 dark:text-slate-400 sm:text-lg">
          Complete guide to supported input audio/video containers, direct media URLs, and exportable transcript formats.
        </p>

        {/* Quick Spec Highlights Strip */}
        <div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">
          <div className="apple-glass-card rounded-2xl p-4 text-center">
            <div className="text-2xl font-bold text-blue-600 dark:text-blue-400">{MAX_MEDIA_UPLOAD_MB} MB</div>
            <div className="text-xs font-medium text-slate-500 dark:text-slate-400 mt-1">Per File Upload</div>
          </div>
          <div className="apple-glass-card rounded-2xl p-4 text-center">
            <div className="text-2xl font-bold text-slate-900 dark:text-white">12+</div>
            <div className="text-xs font-medium text-slate-500 dark:text-slate-400 mt-1">Media Encodings</div>
          </div>
          <div className="apple-glass-card rounded-2xl p-4 text-center">
            <div className="text-2xl font-bold text-indigo-600 dark:text-indigo-400">10 Files</div>
            <div className="text-xs font-medium text-slate-500 dark:text-slate-400 mt-1">Batch Concurrency</div>
          </div>
          <div className="apple-glass-card rounded-2xl p-4 text-center">
            <div className="text-2xl font-bold text-emerald-600 dark:text-emerald-400">4 Types</div>
            <div className="text-xs font-medium text-slate-500 dark:text-slate-400 mt-1">Export Subtitles & Text</div>
          </div>
        </div>
      </header>

      {/* Main Grid: Input Capabilities & Export Specifications */}
      <div className="grid grid-cols-1 gap-8 lg:grid-cols-12">
        {/* Left Column: Input Capabilities (7 cols) */}
        <div className="flex flex-col gap-6 lg:col-span-7">
          {/* Card: Audio & Video Ingestion */}
          <section className="apple-glass-card flex flex-col rounded-3xl p-6 sm:p-8">
            <div className="flex items-center gap-3 mb-6">
              <span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-50 text-blue-600 dark:bg-blue-950/60 dark:text-blue-400 ring-1 ring-blue-500/20">
                <FileAudio className="h-5 w-5" />
              </span>
              <div>
                <h2 className="text-xl font-bold text-slate-950 dark:text-white">Input Capabilities</h2>
                <p className="text-xs text-slate-500 dark:text-slate-400">Multi-format audio and video processing engine</p>
              </div>
            </div>

            {/* Audio Section */}
            <div className="mb-6">
              <div className="flex items-center gap-2 mb-3">
                <FileAudio className="h-4 w-4 text-slate-500 dark:text-slate-400" />
                <h3 className="text-sm font-semibold text-slate-800 dark:text-slate-200">Supported Audio Formats</h3>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                {AUDIO_FORMATS.map((item) => (
                  <div
                    key={item.ext}
                    className="flex items-start gap-3 rounded-2xl border border-slate-200/70 bg-slate-50/70 dark:border-slate-800/80 dark:bg-slate-900/60 p-3 transition-colors hover:border-blue-500/30"
                  >
                    <span className="rounded-lg bg-blue-100/70 dark:bg-blue-950/80 px-2 py-1 font-mono text-xs font-bold text-blue-700 dark:text-blue-300">
                      .{item.ext.toLowerCase()}
                    </span>
                    <div className="min-w-0">
                      <div className="text-xs font-semibold text-slate-900 dark:text-slate-200 truncate">{item.name}</div>
                      <div className="text-[11px] text-slate-500 dark:text-slate-400 truncate">{item.desc}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Video Section */}
            <div className="mb-6">
              <div className="flex items-center gap-2 mb-3">
                <FileVideo className="h-4 w-4 text-slate-500 dark:text-slate-400" />
                <h3 className="text-sm font-semibold text-slate-800 dark:text-slate-200">Supported Video Formats</h3>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                {VIDEO_FORMATS.map((item) => (
                  <div
                    key={item.ext}
                    className="flex items-start gap-3 rounded-2xl border border-slate-200/70 bg-slate-50/70 dark:border-slate-800/80 dark:bg-slate-900/60 p-3 transition-colors hover:border-indigo-500/30"
                  >
                    <span className="rounded-lg bg-indigo-100/70 dark:bg-indigo-950/80 px-2 py-1 font-mono text-xs font-bold text-indigo-700 dark:text-indigo-300">
                      .{item.ext.toLowerCase()}
                    </span>
                    <div className="min-w-0">
                      <div className="text-xs font-semibold text-slate-900 dark:text-slate-200 truncate">{item.name}</div>
                      <div className="text-[11px] text-slate-500 dark:text-slate-400 truncate">{item.desc}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Cloud & URL Links */}
            <div className="rounded-2xl border border-slate-200/80 bg-gradient-to-r from-blue-50/50 to-indigo-50/50 dark:border-slate-800/80 dark:from-blue-950/20 dark:to-indigo-950/20 p-4">
              <div className="flex items-start gap-3">
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-blue-500/10 text-blue-600 dark:text-blue-400">
                  <Globe className="h-4 w-4" />
                </div>
                <div>
                  <h4 className="text-sm font-semibold text-slate-900 dark:text-white">Web Link & Streaming Ingestion</h4>
                  <p className="mt-1 text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                    Paste direct audio/video web links (HTTPS) or YouTube video URLs. The engine streams the audio stream directly without requiring manual downloads.
                  </p>
                </div>
              </div>
            </div>

            {/* Audio Best Practices */}
            <div className="mt-6 border-t border-slate-200/70 dark:border-slate-800/70 pt-6">
              <h3 className="text-sm font-semibold text-slate-900 dark:text-white mb-3">Optimal Audio Recommendations</h3>
              <ul className="space-y-2.5 text-xs text-slate-600 dark:text-slate-300">
                <li className="flex items-center gap-2.5">
                  <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-500" />
                  <span><strong>Sample Rate:</strong> 16 kHz to 48 kHz recommended for optimal acoustic fidelity.</span>
                </li>
                <li className="flex items-center gap-2.5">
                  <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-500" />
                  <span><strong>Channels:</strong> Mono or Stereo (multi-channel audio is intelligently downmixed).</span>
                </li>
                <li className="flex items-center gap-2.5">
                  <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-500" />
                  <span><strong>Long Recordings:</strong> Media exceeding 10–15 minutes is automatically chunked and processed seamlessly.</span>
                </li>
                <li className="flex items-center gap-2.5">
                  <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-500" />
                  <span><strong>Clarity:</strong> Minimize heavy background music and acoustic reverb for 99%+ accuracy.</span>
                </li>
              </ul>
            </div>
          </section>
        </div>

        {/* Right Column: Export Specifications & Interactive Sample Preview (5 cols) */}
        <div className="flex flex-col gap-6 lg:col-span-5">
          <section className="apple-glass-card flex flex-col rounded-3xl p-6 sm:p-8">
            <div className="flex items-center gap-3 mb-6">
              <span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-600 dark:bg-emerald-950/60 dark:text-emerald-400 ring-1 ring-emerald-500/20">
                <FileText className="h-5 w-5" />
              </span>
              <div>
                <h2 className="text-xl font-bold text-slate-950 dark:text-white">Export Formats</h2>
                <p className="text-xs text-slate-500 dark:text-slate-400">Interactive preview and specifications</p>
              </div>
            </div>

            {/* Interactive Format Switcher Tabs */}
            <div className="mb-4 flex flex-wrap gap-1.5 rounded-2xl bg-slate-100/90 dark:bg-slate-900/90 p-1.5 ring-1 ring-slate-200/60 dark:ring-slate-800/60">
              {(Object.keys(EXPORT_FORMATS) as ExportFormatKey[]).map((key) => {
                const format = EXPORT_FORMATS[key]
                const isActive = activeTab === key
                return (
                  <button
                    key={key}
                    onClick={() => setActiveTab(key)}
                    className={`flex-1 min-w-[65px] rounded-xl px-2.5 py-1.5 text-xs font-semibold transition-all cursor-pointer ${
                      isActive
                        ? 'bg-white text-slate-900 shadow-xs dark:bg-blue-600 dark:text-white'
                        : 'text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white'
                    }`}
                  >
                    {format.extension.toUpperCase()}
                  </button>
                )
              })}
            </div>

            {/* Active Format Details */}
            <div className="mb-4 rounded-2xl border border-slate-200/80 bg-slate-50/60 dark:border-slate-800/80 dark:bg-slate-900/50 p-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-sm font-bold text-slate-900 dark:text-white">
                    {EXPORT_FORMATS[activeTab].name}{' '}
                    <span className="font-mono text-xs text-blue-600 dark:text-blue-400">
                      ({EXPORT_FORMATS[activeTab].extension})
                    </span>
                  </h3>
                  <span className="mt-1 inline-block rounded-full bg-blue-50 dark:bg-blue-950/60 px-2.5 py-0.5 text-[10px] font-semibold text-blue-600 dark:text-blue-400 ring-1 ring-blue-500/20">
                    {EXPORT_FORMATS[activeTab].badge}
                  </span>
                </div>
                <span className="text-[11px] text-slate-500 dark:text-slate-400 text-right">
                  Best with: <br />
                  <strong className="text-slate-800 dark:text-slate-200">{EXPORT_FORMATS[activeTab].bestFor}</strong>
                </span>
              </div>
              <p className="mt-2 text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                {EXPORT_FORMATS[activeTab].desc}
              </p>
            </div>

            {/* Interactive Code Preview Box */}
            <div className="relative flex flex-col rounded-2xl border border-slate-800 bg-slate-950 p-4 shadow-inner">
              <div className="flex items-center justify-between border-b border-slate-800/80 pb-2 mb-3">
                <span className="flex items-center gap-1.5 font-mono text-[11px] text-slate-400">
                  <FileCode className="h-3.5 w-3.5 text-blue-400" />
                  sample_transcript{EXPORT_FORMATS[activeTab].extension}
                </span>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1 rounded-md bg-slate-800/80 hover:bg-slate-800 px-2.5 py-1 text-[11px] font-medium text-slate-200 transition-colors active:scale-95 cursor-pointer"
                  title="Copy sample snippet"
                >
                  {copied ? (
                    <>
                      <Check className="h-3 w-3 text-emerald-400" />
                      <span className="text-emerald-400">Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="h-3 w-3 text-slate-400" />
                      <span>Copy</span>
                    </>
                  )}
                </button>
              </div>

              <pre className="overflow-x-auto max-h-56 font-mono text-[11px] leading-relaxed text-slate-300 whitespace-pre-wrap selection:bg-blue-500/30">
                {EXPORT_FORMATS[activeTab].sample}
              </pre>
            </div>

            {/* Software Ecosystem Compatibility */}
            <div className="mt-6 border-t border-slate-200/70 dark:border-slate-800/70 pt-6">
              <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-3">
                Broad Ecosystem Compatibility
              </h3>
              <div className="flex flex-wrap gap-1.5">
                {COMPATIBLE_TOOLS.map((tool) => (
                  <span
                    key={tool}
                    className="rounded-lg border border-slate-200/70 bg-white/70 dark:border-slate-800 dark:bg-slate-900/60 px-2.5 py-1 text-[11px] font-medium text-slate-700 dark:text-slate-300"
                  >
                    {tool}
                  </span>
                ))}
              </div>
            </div>
          </section>
        </div>
      </div>

      {/* Bottom Call to Action Section */}
      <section className="mt-12 overflow-hidden rounded-3xl apple-glass p-8 text-center relative">
        <div className="relative z-10 mx-auto max-w-xl">
          <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-b from-blue-500 to-blue-600 text-white shadow-lg shadow-blue-500/30">
            <UploadCloud className="h-6 w-6" />
          </div>
          <h2 className="text-2xl font-bold tracking-tight text-slate-950 dark:text-white sm:text-3xl">
            Ready to Transcribe Your Media?
          </h2>
          <p className="mt-2 text-sm text-slate-600 dark:text-slate-400">
            Upload single files or multi-file batches up to {MAX_MEDIA_UPLOAD_MB} MB each. High precision speech recognition with export in seconds.
          </p>
          <div className="mt-6 flex flex-wrap items-center justify-center gap-3">
            <Link
              href="/"
              className="apple-btn-primary inline-flex items-center gap-2 rounded-full px-5 py-2.5 text-sm font-semibold text-white shadow-md transition-transform active:scale-95"
            >
              <span>Transcribe Now</span>
              <ArrowRight className="h-4 w-4" />
            </Link>
            <Link
              href="/history"
              className="inline-flex items-center gap-2 rounded-full border border-slate-200/80 bg-white/90 dark:border-slate-700 dark:bg-slate-900/90 px-5 py-2.5 text-sm font-semibold text-slate-700 dark:text-slate-200 shadow-xs transition-all hover:bg-slate-50 dark:hover:bg-slate-800"
            >
              <span>View Past Jobs</span>
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}
